server:
  port: 8081
  
logging:
  level:
    com.itau.system: info
  file.name: logs/spring-boot-logger-log4j2.log

spring:
  kafka:
    consumer:
      group-id: "default"
  mail:
    host: smtp.gmail.com
    port: 587
    username: renan8r@gmail.com
    password: kqtz inkg eqcd wagh
    sendTo: 'renan10r_@hotmail.com'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      
      
topic:
  name: user.email