server:
  port: 8081
  
logging:
  level:
    com.itau.system: info
  file.name: logs/spring-boot-logger-log4j2.log

spring:
  boot.admin.client.url: http://localhost:8080
  boot.admin.client.instance.name: 'Consumer'
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: kafka:29092, localhost:9092
      group-id: "default"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  mail:
    host: smtp.gmail.com
    port: 587
    username: renan8r@gmail.com
    password: kqtz inkg eqcd wagh
    sendTo: 'renan10r_@hotmail.com'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

topic:
  name: user.email
  
consumer:
  timer: 2
  time-unit: MINUTES
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health.show-details: always
    logfile.external-file=: logs/spring-boot-logger-log4j2.log
