# a very minimal declarative config file
_format_version: "2.1"
_transform: true

services:
- host: backend
  name: api-users
  port: 8080
  protocol: http
  path: /api/users
  routes:
  - paths:
    - /users
    methods:
    - PUT
    - GET
    - POST
    - DELETE
    - OPTIONS
    strip_path: true