server:
  port: 8080

logging:
  level:
    com.itau.system: info

spring:
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver: org.h2.Driver
    username: su
    password: su
  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update  
