server:
  port: 8080

logging:
  level:
    com.itau.system: info
  file.name: logs/spring-boot-logger-log4j2.log

spring:
  kafka:
    producer:
      acks: -1
      bootstrap-servers: kafka:29092, localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  boot:
    admin:
      api-path: /api
      routes.endpoints: env, metrics, trace, jolokia, info, configprops
      discovery:
        ignored-services: gateway-service
      client:
        username: su
        password: su
        url: http://localhost:8080
      instance.metadata.user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
  security.user:
    name: su
    password: su

  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver: org.h2.Driver
    username: su
    password: su

  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update
       
topic:
  name: user.email

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health.show-details: always
    logfile.external-file=: logs/spring-boot-logger-log4j2.log
